install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

before_install:
  - sudo apt-get install tree

language: erlang
otp_release:
  - 20.3
  - 20.2

script:
  - ERL_INTERFACE_DIR="$(ls -d ~/otp/*/lib/erl_interface*/)"
  - tree $ERL_INTERFACE_DIR
  - ./rebar3 compile
  - ./rebar3 eunit
